# Generated by Django 3.0.3 on 2020-02-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
