# Generated by Django 3.0.3 on 2020-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(max_length=200, verbose_name='Type of work')),
                ('amount_done', models.IntegerField(verbose_name='Work done')),
            ],
        ),
    ]
