# Generated by Django 3.0.3 on 2020-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200217_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedBookingDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restricted', models.DateTimeField(verbose_name='Restrict Date')),
            ],
        ),
    ]
