# Generated by Django 3.0.3 on 2020-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_appointment_bookedfor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='booked_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-03'),
            preserve_default=False,
        ),
    ]
