# Generated by Django 3.0.3 on 2020-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200220_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='medicalaid number'),
        ),
    ]
