# Generated by Django 3.0.3 on 2020-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_appointment_appointment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='bookedfor',
            field=models.CharField(blank=True, default='willard', max_length=400, null=True),
        ),
    ]
